spring:
  application:
    name: Database
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: devUser
    password: "devPass"
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  custom:
    db:
      credentials:
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}